/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GraO0nJ3ArS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  CollapsibleTrigger,
  CollapsibleContent,
  Collapsible,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";

export function Blogheader() {
  return (
    <header className="bg-gray-900 text-white py-4 px-6 md:px-8 lg:px-10">
      <div className="container mx-auto flex items-center justify-between">
        <div className="flex items-center">
          <Link className="text-2xl font-bold mr-6" href="#">
            My Blog
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:text-gray-300" href="#">
              Home
            </Link>
            <Collapsible className="relative">
              <CollapsibleTrigger className="flex items-center space-x-2 hover:text-gray-300 cursor-pointer">
                <span>Categories</span>
                <ChevronDownIcon className="h-4 w-4" />
              </CollapsibleTrigger>
              <CollapsibleContent className="absolute z-10 bg-gray-900 py-2 px-4 rounded shadow-lg w-48">
                <Link className="block py-1 hover:text-gray-300" href="#">
                  Technology
                </Link>
                <Link className="block py-1 hover:text-gray-300" href="#">
                  Lifestyle
                </Link>
                <Link className="block py-1 hover:text-gray-300" href="#">
                  Travel
                </Link>
                <Link className="block py-1 hover:text-gray-300" href="#">
                  Food
                </Link>
              </CollapsibleContent>
            </Collapsible>
          </nav>
        </div>
        <div className="flex items-center">
          <form className="relative">
            <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500" />
            <Input
              className="bg-gray-800 border-none rounded-full py-2 pl-10 pr-4 focus:outline-none focus:ring-2 focus:ring-white focus:ring-opacity-50"
              placeholder="Search..."
              type="text"
            />
          </form>
        </div>
      </div>
    </header>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
